### ISSUE TITLE
Two Different Package Types in One Shipment Order

### ISSUE THREAD

**Issue by nikunjsilvercayde** [JeremyDunn/php-fedex-api-wrapper#116]
Hello,

I want to create 2 or more packages in one shipment but I have problem that every package has different package type 1 package has custom package (YOUR_PACKAGE) and 2nd package has (FEDEX_EXTRA_LARGE_BOX) and 3rd has different package type. So Let me know how to send multiple package with different package type in single shipment order?

I tried by sending below code..

$rateRequest->RequestedShipment->PackageCount = 2;

//create package line items
$rateRequest->RequestedShipment->RequestedPackageLineItems = [new ComplexType\RequestedPackageLineItem(),new ComplexType\RequestedPackageLineItem()];

//package 1
$rateRequest->RequestedShipment->RequestedPackageLineItems[0]->PackagingType = "FEDEX_SMALL_BOX";
$rateRequest->RequestedShipment->RequestedPackageLineItems[0]->Weight->Value = "1.95";
$rateRequest->RequestedShipment->RequestedPackageLineItems[0]->Weight->Units = SimpleType\WeightUnits::_LB;
$rateRequest->RequestedShipment->RequestedPackageLineItems[0]->Dimensions->Length = 1;
$rateRequest->RequestedShipment->RequestedPackageLineItems[0]->Dimensions->Width = 1;
$rateRequest->RequestedShipment->RequestedPackageLineItems[0]->Dimensions->Height = 7.52;
$rateRequest->RequestedShipment->RequestedPackageLineItems[0]->Dimensions->Units = SimpleType\LinearUnits::_IN;
$rateRequest->RequestedShipment->RequestedPackageLineItems[0]->GroupPackageCount = 1;

//package 2
$rateRequest->RequestedShipment->RequestedPackageLineItems[1]->PackagingType = "FEDEX_EXTRA_LARGE_BOX";
$rateRequest->RequestedShipment->RequestedPackageLineItems[1]->Weight->Value = "22.95";
$rateRequest->RequestedShipment->RequestedPackageLineItems[1]->Weight->Units = SimpleType\WeightUnits::_LB;
$rateRequest->RequestedShipment->RequestedPackageLineItems[1]->Dimensions->Length = 20;
$rateRequest->RequestedShipment->RequestedPackageLineItems[1]->Dimensions->Width = 20;
$rateRequest->RequestedShipment->RequestedPackageLineItems[1]->Dimensions->Height = 10;
$rateRequest->RequestedShipment->RequestedPackageLineItems[1]->Dimensions->Units = SimpleType\LinearUnits::_IN;
$rateRequest->RequestedShipment->RequestedPackageLineItems[1]->GroupPackageCount = 1;

**Comment by kajoldave** [comment]
Hello,
   Can you guide me how to use this
https://github.com/JeremyDunn/php-fedex-api-wrapper/tree/master/src/FedEx/_wsdl
example in wordpress ? I tried many times but not getting proper ouput for
the same.

kindly support me for the same.


Thanks & Regards,

Kajol Dave

Wordpress Developer | Teksun Microsys Pvt LTD

Web : www.teksun.in         | USA: +1 405 404 4162

Direct : +91 851136755     | India : +91 7923299559

ISO 9001:2015 Certified Company | Product Design Engineering | Hardware|
Firmware |

Application Software | Cloud | Web | Mobile | IoT |Big Data | AI |
Prototype | Production |

Feasibility Study | Research | Product Roadmap | Automotive | Wearable |
Tracking |

Healthcare | Semiconductor | Embedded

The content of this email is confidential for the recipient specified in
message only. It is strictly forbidden to share any part of this message
with any part of this message with any third party without consent of the
sender. If you received this message by mistake, please reply to this
message and follow with its deletion, so that we can ensure such a mistake
does not occur in the future.
