### ISSUE TITLE
Fedex production mode it says auth failed,

### ISSUE THREAD

**Issue by Sturtuk** [JeremyDunn/php-fedex-api-wrapper#123]
We are using your package for FedEx operations when using test environment labels are create perfectly, if in production mode it says auth failed, do you know any reason for this?

**Comment by Windtalk3r** [comment]
Did you update your key, password, account, and meter to your production values? They will be different from your test values.

**Comment by Sturtuk** [comment]
Yes, Test keys are working, Live keys not working

**Comment by jameswagoner** [comment]
Just an FYI, this is happening on my end as well. Production keys prove to be working in ecommerce software but used in another app, same issue as OP.

A call to FedEx resulted in a coincidental issue with their production servers, however I have experienced this more than a week ago and any time when I switch to production keys since then. Waiting for their production issues to be cleared up and call again to track down the issue.

**Comment by jameswagoner** [comment]
--UPDATE--

Seems to be that my issue was a wsdl version mismatch with this package and the production keys allowed. I downloaded the latest wsdl from FedEx Web Services and ran the generate command and overwrote the classes. In my case, I just need Tracking Services. This package was last generated with v16 where as v18 is the current version (at least what my production keys match)
