### ISSUE TITLE
src/FedEx/OpenShipService/SimpleType/ServiceType.php no longer exists

### ISSUE THREAD

**Issue by brandonjbegle** [JeremyDunn/php-fedex-api-wrapper#200]
After commit c5385da073cdcba26cf730a7688c952404b6241f 4 days ago:

src/FedEx/OpenShipService/SimpleType/ServiceType.php
src/FedEx/OpenShipService/SimpleType/PackagingType.php

no longer exist on the repository.

Is there a reason for this change?
<img width="1603" alt="Screen Shot 2022-02-18 at 3 57 58 PM" src="https://user-images.githubusercontent.com/22717872/154760507-bcb83f0e-e0f6-4cb5-860d-464997b13241.png">

**Comment by JeremyDunn** [comment]
@brandonjbegle 

Hi from Evansville 👋 

It's because the OpenshipService_v20.wsdl no longer has this type defined and that class should have been deleted when the code was regenerated after updating from v15 to v20. I think I may update the script that generates this code to delete files first so it's obvious to anyone updating a wsdl and generating code that some files should be removed from the repo.

https://github.com/JeremyDunn/php-fedex-api-wrapper/pull/187/files#diff-df094db12113424dfc8bdbe7866e63f1adf2d8a30031737d2510bf4891515b57L5634

<img width="1300" alt="Update_services__tests__examples_and_composer_packages_by_mixisLv_·_Pull_Request__187_·_JeremyDunn_php-fedex-api-wrapper" src="https://user-images.githubusercontent.com/161614/155372102-8fd08367-d942-408f-9ead-4e67b5885afc.png">

**Comment by brandonjbegle** [comment]
Thanks for the response. I ended up seeing that change and we decided to just revert to 6.0.1 so we didn't have to make any changes.
