### ISSUE TITLE
Class missing since v6.0.2 - SimpleType\ServiceType

### ISSUE THREAD

**Issue by czmole** [JeremyDunn/php-fedex-api-wrapper#204]
Hello,

Any reason why _class FedEx\ShipService\SimpleType\ServiceType_ was removed in the last version ?
Or is a bug?

**Comment by czmole** [comment]
Same case for PackagingType 
I have included this is in the PR above
If can not be merged - was it moved to a different place or how should be used?
Thank you!

**Comment by JeremyDunn** [comment]
Hi @czmole Please see the explanation here: https://github.com/JeremyDunn/php-fedex-api-wrapper/issues/200

Are you actually using this class to construct a request to the API?

**Comment by czmole** [comment]
Hi, @JeremyDunn 

Yes, we are using it to detect shipment type and residential status based on some business logic and flags in DB. 

First when we noticed that is missing we switch to using some other class that was still there and was having the same constants defined but felt strange to do such things so we switched to v6.0.1 for now.

**Comment by JeremyDunn** [comment]
Ok, I'm going to revert my latest commit which removed these files and tag a new _patch_ release. `SimpleType/ServiceType` hasn't been part of ShipService since it was updated in 2020, so the next _major_ release will remove this class and others.

History for _wsdl folder:
https://github.com/JeremyDunn/php-fedex-api-wrapper/commits/da74af7dc27500e8210e4b4c7de75e2931d5bf6e/src/FedEx/_wsdl

ShipService v23 with SimpleType/ServiceType:
https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/1d8bf5fe886f8db7d9ff30f09dc3791b8bf48edf/src/FedEx/_wsdl/ShipService_v23.wsdl#L4163

Current ShipService (v28) without SimpleType/ServiceType:
https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/main/src/FedEx/_wsdl/ShipService_v28.wsdl

**Comment by JeremyDunn** [comment]
Ok, I reverted my commit which removed these files and created a new 6.0.3 release.

**Comment by Soetens** [comment]
@JeremyDunn    
Fedex replaced    
`INTERNATIONAL_PRIORITY` with `FEDEX_INTERNATIONAL_PRIORITY`   
 and    
`INTERNATIONAL_PRIORITY_EXPRESS` with `FEDEX_INTERNATIONAL_PRIORITY_EXPRESS`
