### ISSUE TITLE
error When i create pending shipment request- Soap Fault

### ISSUE THREAD

**Issue by muhiddingithub** [JeremyDunn/php-fedex-api-wrapper#36]
With Production Key, production keys are certificated

**Comment by rswyatt** [comment]
I am having the same issue. Only with the test url... I get a SoapFault exception.

**Comment by JeremyDunn** [comment]
Related to the following issues: 

https://github.com/JeremyDunn/php-fedex-api-wrapper/issues/18
https://github.com/JeremyDunn/php-fedex-api-wrapper/issues/34

FedEx has removed the pending shipment functionality from the Ship Service.

It is now part of the Open Ship Service.  I'll add the Open Ship service in the near future.

**Comment by JeremyDunn** [comment]
I was mistaken in my comment about the Open Ship service. Creating a pending shipment through the ShipService still works.

To better troubleshoot your error, examine the raw response returned from the SoapClient. Sometimes the Fatal exception created from the \SoapClient doesn't have the error details.

For example:
```php
$shipServiceRequest = new ShipService\Request();
try {
    $response = $shipServiceRequest->getCreatePendingShipmentReply($createPendingShipmentRequest);
    var_dump($response);
} catch (\Exception $e) {
    echo $shipServiceRequest->getSoapClient()->__getLastResponse();
}
```

The FedEx web service is very picky about date formats.  For example, use 'c' to format in ISO format rather than \DateTime::ISO8601.

**Comment by JeremyDunn** [comment]
I have updated the create pending shipment example. 

https://github.com/JeremyDunn/php-fedex-api-wrapper/blob/master/examples/create-pending-shipment.php

**Comment by harikt** [comment]
In the example `CreatePendingShipmentRequest` class is missing. Or was this a typo ?
